### ISSUE TITLE
No MCmod.info for forge

### ISSUE THREAD

**Issue by denzuko** [Slikrick/RemoteIO#10]
Just adding one little annoyance to the list of parts that should be fixed in the mod.

Would be nice to have a few details in the mcmod.info for forge to parse. Could include a short blup of the mod and links back to the issue tracker here.

**Comment by GirafiStudios** [comment]
Update to 2.4.0.

**Comment by denzuko** [comment]
@GirafiStudios Thanks. had the 2.3B version from curse. Guess I didn't notice the 2.4 version.
