### ISSUE TITLE
No link Nor Author Given

### ISSUE THREAD

**Issue by Badcholo** [Slikrick/RemoteIO#5]
I am using modlister that links to a website to show what mods i am running on the Server.
It does not show your author name or link to your website.

http://modlister.com/server/Mojangsters

I'm unsure if it is something you have to add or if it's on their end.

**Comment by Badcholo** [comment]
<Quetzi> The info is pulled directly out of the mods metadata, if the authors don't set it then it won't show up

**Comment by GirafiStudios** [comment]
The version listed on modlister.com is the old version which had an broken mcmod.info. This is fixed in Remote IO 2.4

**Comment by Badcholo** [comment]
Just making sure everyone gets their deserved credit. Thanks

**Comment by Slikrick** [comment]
Assuming modlister is checking the mcmod.info (which im guessing it is) then yes, in 2.4.0 it should show it correctly. Not a huge issue, im still trying to figure out everyone who has contributed textures and all that, but the authors are correctly stated in the mcmod.info as well as cyanide's website.

**Comment by Badcholo** [comment]
ok, i just updated to 2.4, i'll check in an hour.

**Comment by Slikrick** [comment]
Until otherwise stated going to assume that this is fixed with 2.4.0
